name: ruko_mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.1 <4.0.0' # Using a range is safer for future compatibility

dependencies:
  flutter:
    sdk: flutter
  
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0
  url_launcher: ^6.1.1
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # This is the package that generates your app icons.
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.0

# This section is for Flutter-specific configurations.
flutter:
  uses-material-design: true

  # This section tells your app which asset files to include in the build.
  # It's crucial for the icon generator and for using images in your app.
  assets:
    - assets/logo.png

# This is the configuration block for the app icon generator.
# It tells the package where to find your logo and how to create the icons.
# It is correctly placed at the root level (no indentation ).
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
